### ISSUE TITLE
JSX Component not recognized as scope reference

### ISSUE THREAD

**Issue by delca85** [eslint/eslint-scope#61]
Hi!
Trying to fix [this](https://github.com/facebook/react/issues/18051) bug in `eslint-plugin-react-hooks` related to `exhaustive-deps` rule I could have found out something that looks like a bug in the way the `scopeManager` handles `JSX Component`.

According to me, when a `JSX Component` is instantiated no reference is added to the scope `references` array.
For example, this test fails:

```js
const ast = espree(`
  function Example({ component: Component }) {
    const myFunction = (data) => (<Component data={data}/>)
  }
`);

const scopeManager = analyze(ast);
const scope = scopeManager.scopes[2];
expect(scope.references).to.have.length(2); // [data, component]
```

The actual `scope.references` has length 1 and the only node inside it is the one named `data`.

I have already worked on a PR but I would like to know if this looks like to a legit bug to you or I have misunderstood something.

Thanks for your time!

**Comment by nzakas** [comment]
JSX itself does not imply any sort of references, it's React that overlays the concept of variable references on top of JSX.

It was an intentional design decision not to implement React-specific logic in ESLint, which is why you're seeing this behavior. We're not going to change that approach so you'd need to account for this in your plugin.

**Comment by delca85** [comment]
Ok, thank you very much for your explanation.

I am going to close this issue because it's not a real issue. 

Thanks again.
