### ISSUE TITLE
[Question] How to find reference for a class property used in a non-computed MemberExpression node 

### ISSUE THREAD

**Issue by testmynamelist** [eslint/eslint-scope#65]
# Background

I want to get a list of referencers for a class property, one of which is in a MemberExrepssion node, but it failed to be listed

Here below is my source code:

As you can see, class property `aProperty` is referenced in a `Property` node, the node value is a MemberExpression node, this node has `computed` property as false.

```
export class Hi {
  private aProperty = 'Test';
  private getAProperty() {
    this.generate({
      prop: this.aProperty
    });
  }
}

```

# What I have checked

After debugging, I found below codes in the [referencer](https://github.com/eslint/eslint-scope/blob/master/lib/referencer.js), and found it's the node.computed condition prevents the above class property being reference.

```
    MemberExpression(node) {
        this.visit(node.object);
        if (node.computed) {
            this.visit(node.property);
        }
    }
```

# My Question

Is it possible to get officially remove this node.computed condition? e.g. in my case if we are using `this.aProperty` instead of `this[aProperty]`.

Would appreciate if you can help~

**Comment by mdjermanovic** [comment]
Hi @testmynamelist!

This looks like a typescript code, are you maybe using [@typescript-eslint/scope-manager](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/scope-manager) or some other library instead of `eslint-scope`?

As for ES class fields, `eslint-scope` doesn't support them yet, since it's still an experimental stage 3 syntax. 

Regardless of that, I'm not sure if a scope analyzer should treat class fields as variables (and `this.aProperty` or `this.#aProperty` as references) at all, but we'll think about that when this syntax reaches stage 4.

> Is it possible to get officially remove this node.computed condition? e.g. in my case if we are using this.aProperty instead of this[aProperty].

That change alone would break scope analysis. For example, in this code:

```js
let foo;

obj.foo;
```

`foo` in `obj.foo` would mistakenly become a reference to the variable `foo`.

**Comment by testmynamelist** [comment]
@mdjermanovic ,

Thank you for your reply!

yes I am using eslint-scope like below, for my custom eslint rule for typescript

```
    const scope = context.getScope();

    function createReferenceMap(scope, outReferenceMap = new Map()) {
      for (let reference of scope.references) {
        outReferenceMap.set(reference.identifier, reference);
      }
      for (const childScope of scope.childScopes) {
        createReferenceMap(childScope, outReferenceMap);
      }

      return outReferenceMap;
    }
```

It would be really helpful if this.aProperty could be referenced, not sure if there are any workaround?

**Comment by mdjermanovic** [comment]
Thanks for clarifying! I thought you might be using the `eslint-scope` library directly.

Since this is about usage from an ESLint rule, and the rule is intended to work with typescript code, I'm guessing the rule will be used with `@typescript-eslint/parser`?

If that's the case, the rule will actually work with [@typescript-eslint/scope-manager](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/scope-manager), not with `eslint-scope` (parsers can provide their own scope analysis to replace the built-in `eslint-scope`), so this seems to be a question for the `typescript-eslint` repository:

https://github.com/typescript-eslint/typescript-eslint

**Comment by testmynamelist** [comment]
@mdjermanovic Yes you are right, my rule is used with @typescript-eslint/parser. Thanks very much for guiding, I got it now, it should go to the [@typescript-eslint/scope-manager](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/scope-manager) repo,  sorry to have had your time on it!

**Comment by testmynamelist** [comment]
Moved issue to [[@typescript-eslint/scope-manager] The property of a non-computed MemberExpression node is not referenced · Issue #2534 · typescript-eslint/typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/2534)
