### ISSUE TITLE
Allow `ecmaVersion` to be `'latest'`?

### ISSUE THREAD

**Issue by fisker** [eslint/eslint-scope#74]
I'm not sure if this make sense to change here, but parsers like `@babel/eslint-parser` pass `ecmaVesion` from `eslintrc` directly to `eslint-scope`, we need to make change in the parser or `eslint-scope` to understand `'latest'`.

RR in babel codebase https://github.com/babel/babel/pull/13638, [review comment](https://github.com/babel/babel/pull/13638#discussion_r684624843)

**Comment by nzakas** [comment]
ESLint doesn't pass "latest" around. It is [normalized](https://github.com/eslint/eslint/blob/1d2213deb69c5901c1950bbe648aa819e7e742ed/lib/linter/linter.js#L442) to the latest ecmaVersion.

Honestly, eslint-scope doesn't really need ecmaVersion. The only difference is between 5 and 6+, for `let` and `const`. Even then we probably don't need the setting because an ES5 AST won't have `let` or `const`.

**Comment by nzakas** [comment]
@fisker any other points I’m missing here?

**Comment by fisker** [comment]
> ESLint doesn't pass "latest" around. 

I think `@babel/eslint-parser` pass it to [`eslint-scope`](https://github.com/babel/babel/blob/936fe405e05e09a976103ec67a1dcd6e3a25bcb2/eslint/babel-eslint-parser/src/analyze-scope.cjs#L353), so the real question is should we handle `"latest"` here or `@babel/eslint-parser`.

**Comment by nzakas** [comment]
Ah I see. I’d suggest you normalize “latest” to a version number. But as I mentioned, the only thing that matters is 5 vs 6. You can probably just pass 6 all the time.

**Comment by fisker** [comment]
Thank you, I'll try to make the change in babel then.

**Comment by nzakas** [comment]
Sounds good.
